# Main config file for icon theme.
theme = "hugo-icon"
baseURL = "https://11042020.github.io/"
languageCode = "fr-FR"
title = "Mariage Dorra & Dhia"

# Metadata
[params]
  author = "Dorra & Dhia"
  description = "Mariage Dorra & Dhia<br/>11 avril 2020"

# Hero section (from here on is for icon theme)
[params.hero]
  img = "images/header_flower.jpeg"
  title = ""
  description = ""

[params.herofemmes]
  img = "images/header_flower.jpeg"
  title = ""
  description = ""

# Navigation section
[params.nav]
  services = "Infos"
  servicesfemmes = "Infos2"
  #logo = "images/hero_bg.jpg"

[markup.goldmark.renderer]
unsafe= true
# Services section
[params.services]
  enable = true
  title = "Infos"
  description = """
 <blockquote dir="rtl">
 <p>Ø¨ÙØ³Ù’Ù…Ù Ù±Ù„Ù„ÙÙ‘Ù°Ù‡Ù Ù±Ù„Ø±ÙÙ‘Ø­Ù’Ù…ÙÙ°Ù†Ù Ù±Ù„Ø±ÙÙ‘Ø­ÙÙŠÙ…Ù</p>
<p>Ù±Ù„Ø³ÙÙ‘Ù„ÙØ§Ù…Ù Ø¹ÙÙ„ÙÙŠÙ’ÙƒÙÙ…Ù’ ÙˆÙØ±ÙØ­Ù’Ù…ÙØ©Ù Ù±Ù„Ù„ÙÙ‘Ù°Ù‡Ù ÙˆÙØ¨ÙØ±ÙÙƒÙØ§ØªÙÙ‡Ù</p>
</blockquote>

<p>Bonjour &agrave; tous,</p>
<p>Les familles Ben Naser et Ayachi ont l&rsquo;honneur de vous convier au repas de c&eacute;l&eacute;bration du mariage de leurs enfants Dhia et Dorra.</p>
<p>Au vu des r&egrave;gles de confinement et par mesure de s&eacute;curit&eacute;, nous respecterons les r&egrave;gles impos&eacute;es par la mairie et la mosqu&eacute;e.&nbsp;</p>
<p>Ainsi, nous nous ferons une joie de tous vous retrouver le <b>18 juillet 2020 de 14h &agrave; 18h</b> au</p>
<p><b>108 de la Grange Colombe &agrave; Rambouillet (78)</b> .</p>
<p>Au vu du nombre de convives limit&eacute;s, pensez svp &agrave; confirmer votre venue dans le document ci dessous.</p>
<p>Nous comptons sur votre pr&eacute;sence pour partager avec nous ce moment de bonheur.</p>
<blockquote dir="rtl">
<p>Ø¨ÙØ³Ù’Ù…Ù Ù±Ù„Ù„ÙÙ‘Ù°Ù‡Ù Ù±Ù„Ø±ÙÙ‘Ø­Ù’Ù…ÙÙ°Ù†Ù Ù±Ù„Ø±ÙÙ‘Ø­ÙÙŠÙ…Ù</p>
<p>Ù±Ù„Ø³ÙÙ‘Ù„ÙØ§Ù…Ù Ø¹ÙÙ„ÙÙŠÙ’ÙƒÙÙ…Ù’ ÙˆÙØ±ÙØ­Ù’Ù…ÙØ©Ù Ù±Ù„Ù„ÙÙ‘Ù°Ù‡Ù ØªØ¹Ø§Ù„Ù‰ ÙˆÙØ¨ÙØ±ÙÙƒÙØ§ØªÙÙ‡Ù</p>
<p>Ø­Ø§Ù„ÙˆÙ† Ø£Ù‡Ù„Ø§ ÙˆÙ†Ø§Ø²Ù„ÙˆÙ† Ø³Ù‡Ù„Ø§...</p>
<p>ØªØªØ´Ø±Ù Ø¹Ø§Ø¦Ù„ØªØ§ Ø§Ø¨Ù† Ù†ØµØ± ÙˆØ§Ù„Ø¹ÙŠØ§Ø´ÙŠ Ø¨Ø§Ø³ØªØ¯Ø¹Ø§Ø¦ÙƒÙ… Ù„Ù„ØºØ¯Ø§Ø¡ Ø§Ù„Ø°ÙŠ ØªÙ†Ø¸Ù…Ù‡ Ø§Ø­ØªÙØ§Ø¡ Ø¨Ø²ÙˆØ§Ø¬ Ø§Ø¨Ù†ÙŠÙ‡Ù…Ø§ Ø¶ÙŠØ§Ø¡ ÙˆØ¯Ø±Ø©...</p>
<p>Ù…Ø¹ Ø§Ù„ØªØ²Ø§Ù…Ù†Ø§ Ø¨Ù‚ÙˆØ§Ø¹Ø¯ Ø§Ù„Ø­Ø¸Ø± Ø§Ù„ØµØ­ÙŠ ÙÙŠ Ø§Ù„Ø¨Ù„Ø¯ÙŠØ© ÙˆØ¨Ø§Ù„Ù…Ø³Ø¬Ø¯ØŒ ÙØ¥Ù†Ù‡ ÙŠØ³Ø±Ù†Ø§ Ø­Ø¶ÙˆØ±ÙƒÙ… Ø¬Ù…ÙŠØ¹Ø§ Ù…Ø¹Ù†Ø§ ÙŠÙˆÙ… Ø§Ù„Ø³Ø¨Øª 27 Ø°Ùˆ Ø§Ù„Ù‚Ø¹Ø¯Ø© 1441Ù‡ØŒ Ø§Ù„Ù…ÙˆØ§ÙÙ‚ Ù„ÙŠÙˆÙ… 18 Ø¬ÙˆÙŠÙ„ÙŠØ© 2020 ØŒ ÙˆØ°Ù„Ùƒ Ù…Ù† &nbsp;Ø§Ù„Ø³Ø§Ø¹Ø© Ø§Ù„Ø«Ø§Ù†ÙŠØ© Ø¨Ø¹Ø¯ Ø§Ù„Ø¸Ù‡Ø± Ø§Ù„Ù‰ Ø§Ù„Ø³Ø§Ø¯Ø³Ø© ÙÙŠ :</p>
<p>108 de la Grange Colombe &agrave; Rambouillet (78)&nbsp;</p>
<p>Ùˆ Ø¥Ø° ÙƒÙ†Ø§ Ù…Ø·Ø§Ù„Ø¨ÙŠÙ† Ø¨ØªØ­Ø¯ÙŠØ¯ Ø¹Ø¯Ø¯ Ø§Ù„Ø­Ø§Ø¶Ø±ÙŠÙ† &nbsp;ØŒ ÙØ±Ø¬Ø§Ø¤Ù†Ø§ Ø¥Ù„ÙŠÙƒÙ… Ø£Ù† ØªØªÙØ¶Ù„ÙˆØ§ &nbsp;Ø¨ØªØ£ÙƒÙŠØ¯ Ø­Ø¶ÙˆØ±ÙƒÙ… Ù…Ø¹Ù†Ø§ ÙÙŠ Ø§Ù„Ø§Ø³ØªÙ…Ø§Ø±Ø© Ø§Ù„Ù„Ø§Ø­Ù‚Ø© ØŒ ÙØ°Ù„Ùƒ Ù…Ù†ÙƒÙ… ÙØ¶Ù„ ÙˆÙ„Ù†Ø§ Ø´Ø±Ù...</p>
<p>ÙˆÙ„ÙƒÙ… Ø§Ù„Ø¹Ø§Ù‚Ø¨Ø© ÙÙŠ Ø§Ù„Ø£ÙØ±Ø§Ø­ ÙˆØ§Ù„Ù…Ø³Ø±Ø§Øª</p>
</blockquote>

"""

  
  [[params.services.item]]
    icon = "icon-calendar"
    title = "Reservation"
    description = "Nous espÃ©rons vraiment que vous pourrez y assister !  Merci de rÃ©pondre en remplissant le <a href='https://forms.gle/RTQGUYkcRAWCfxPn9' target='_blank'>formulaire suivant</a>"


#Les familles Ben Naser et Ayachi ont lâ€™honneur de vous convier au mariage de leurs enfants Dhia et Dorra qui sera cÃ©lÃ©brÃ©le 18 juillet 2020 de 14h Ã  18h au 108 de la Grange Colombe Ã  Rambouillet (78). 
#Dans le prolongement de la cÃ©rÃ©monie, nous vous invitons Ã  partager un moment convivial autour dâ€™un cocktail au sein de la Mairie jusquâ€™Ã  12h30. 
#Nous comptons sur votre prÃ©sence pour partager avec nous ce moment de bonheur.

  [[params.services.item]]
    icon = "icon-present"
    title = "Cagnotte"
    description = "<a href='https://paypal.me/pools/c/8mQdcPAGFe' target='_blank'>Une cagnotte</a> pour nous aider durant nos premiers mois de vie commune est ouverte ici ğŸ˜Š mais votre prÃ©sence sera votre plus beau cadeau ! "

  [[params.services.item]]
    icon = "icon-camera"
    title = "Photos"
    description = "Voici <a href='https://photos.app.goo.gl/1pgGoWwRZmVeU5iU6' target='_blank'>l'album Google photo collaboratif</a>, vous pouvez y ajouter toutes vos photos et retrouvez les nÃ´tres."

[params.servicesfemmes]
  enable = true
  title = "Informations"
  description = """
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'>Ceci est la partie r&eacute;serv&eacute;e aux femmes !&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'>Bienvenue &agrave; toutes sur cette page secr&egrave;te. En esp&eacute;rant que cette fois-ci soit la bonne, la nouvelle date de <strong>l&rsquo;Outeya&nbsp;</strong>(<em>soir&eacute;e de jeunes filles en tunisien</em>) est pr&eacute;vue le samedi <strong>11 juillet&nbsp;</strong>! Le lieu n&rsquo;a pas chang&eacute;, la maison reste la m&ecirc;me, pour rappel :&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong>L&rsquo;adresse exacte</strong> : 116 Grand Rue, 67430 Diemeringen, France</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:35.4pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><u><span style='font-family:"Segoe UI Emoji",sans-serif;'>ğŸŒ±</span> Pour les &eacute;colos de Strasbourg (et d&rsquo;ailleurs)</u> : c&rsquo;est &agrave; 7 minutes &agrave; pieds de la gare de Diemeringen, il y a un train par heure environ.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:35.4pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><u><span style='font-family:"Segoe UI Emoji",sans-serif;'>ğŸš—</span> Pour les autres</u> : un lien &laquo; <strong>covoiturage</strong> &raquo; est disponible en bas (remplissez-le le plus t&ocirc;t possible svp).&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'>La maison peut h&eacute;berger environ 40 personnes. Venant de tout horizon, vous &ecirc;tes naturellement toutes invit&eacute;es &agrave; <strong>dormir sur place samedi 11 juillet. <u>N&rsquo;oubliez pas :&nbsp;</u></strong></p>
<ul style="list-style-type: undefined;">
    <li>Votre <strong>linge de lit</strong> : drap, petite couette (ou un sac de couchage), coussin&nbsp;</li>
    <li>Votre <strong>maillot de bain&nbsp;</strong>(donc on pense &agrave; une serviette, un s&egrave;che-cheveux et des tongs&hellip;)</li>
    <li>Pour ne pas salir la maison, venez avec des <strong>pantoufles</strong> please !! Ou id&eacute;alement, des patins comme &agrave; la maternelle</li>
    <li>Pr&eacute;voyez pour la journ&eacute;e un<strong>&nbsp;t-shirt blanc&nbsp;</strong>et un <strong>jeans bleu&nbsp;</strong>pour les photos&nbsp;</li>
    <li>Bien s&ucirc;r, n&rsquo;oubliez pas de quoi vous faire belle pour la soir&eacute;e, apportez un petit <strong>miroir</strong>, la maison n&rsquo;en compte pas beaucoup. &nbsp;</li>
</ul>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'>L&rsquo;id&eacute;al est <strong>d&rsquo;arriver samedi 11 juillet &agrave; 10h, le d&eacute;part est pr&eacute;vu dimanche 12 juillet 10h.&nbsp;</strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'>La maison est lou&eacute;e de vendredi 10 juillet apr&egrave;s-midi, &agrave; dimanche 12 juillet 11h, voici le d&eacute;roulement (inshaAllah) :&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong>Vendredi 10 juillet d&egrave;s 19h</strong> : r&eacute;ception pour les invit&eacute;es de ma m&egrave;re et de ma belle-m&egrave;re (ces invit&eacute;es dormiront sur place), cette soir&eacute;e se voudra tr&egrave;s traditionnelle (ambiance Oum-Kalthoum).&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'>&nbsp;<strong><span style='font-family:"Segoe UI Emoji",sans-serif;'>â›”</span> Pour mes copines qui viennent de loin</strong> et ne peuvent venir que d&egrave;s vendredi soir, <strong>pr&eacute;venez-moi</strong> le plus t&ocirc;t possible svp, un lit vous sera r&eacute;serv&eacute; et je vous accueillerai avec plaisir d&egrave;s vendredi soir.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong>Samedi&nbsp;</strong>: afin d&rsquo;avoir plus de temps pour profiter de vous qu&rsquo;une soir&eacute;e classique, et que vous puissiez vous rencontrer mutuellement, je vous invite &agrave; partager avec moi une journ&eacute;e d&rsquo;&eacute;t&eacute; que nous rendrons, je l&rsquo;esp&egrave;re, inoubliable.&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'>Je ne connais pas le d&eacute;roulement de la journ&eacute;e de samedi, &ccedil;a restera une surprise pour moi comme pour vous ! Tout ce que je sais, c&rsquo;est que ma s&oelig;ur et son &eacute;quipe se sont charg&eacute;s des activit&eacute;s qui nous attendent. Si vous avez une question ou un imp&eacute;ratif pour l&rsquo;organisation du samedi, vous pouvez contacter mon t&eacute;moin, la meilleure s&oelig;ur que la terre ait port&eacute;e : Safia : <a href="mailto:safiaaya@hotmail.com">safiaaya@hotmail.com</a>&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong>Samedi soir :&nbsp;</strong>Soir&eacute;e ! Pas de DJ pr&eacute;vu, allez vite nourrir la playlist du bas&nbsp;<span style='font-family:"Segoe UI Emoji",sans-serif;'>ğŸ˜Š</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong>Dimanche</strong> : repos, petit d&eacute;jeuner, rangement de la maison et d&eacute;part avant 11h &agrave; pr&eacute;voir&nbsp;<span style='font-family:"Segoe UI Emoji",sans-serif;'>â˜¹</span>.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'>Nombreuses sont celles qui ont insist&eacute; et m&rsquo;ont demand&eacute; ce que je voulais comme cadeau de mariage, je vois renvoie vers le lien de la cagnotte plus bas. &nbsp;&Ccedil;a me permettra de me faire plaisir et d&rsquo;&eacute;taler l&rsquo;achat de vos cadeaux sur les semaines prochaines.&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'>J&rsquo;esp&egrave;re vous retrouver toutes dans le meilleur de votre forme. Je suis impatiente de partager ce petit &eacute;v&egrave;nement avec vous ! Ne vous inqui&eacute;tez pas sur toutes les formalit&eacute;s parall&egrave;les, pensez qu&rsquo;il s&rsquo;agit d&rsquo;un jour entre nous avec une ambiance &agrave; la bonne franquette. Concernant les repas, mon p&egrave;re a voulu s&#39;en charger. Pour ne pas qu&#39;il reste sur place, il viendra juste nous d&eacute;poser les plats, je compte sur vos petites mains pour m&rsquo;aider &agrave; mettre la table et la d&eacute;barrasser ! Et pour la vaisselle, chacun lave ses couverts&nbsp;<span style='font-family:"Segoe UI Emoji",sans-serif;'>â¤.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'>&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'>Plein plein de bisous,&nbsp;</p>
<p><span style='font-size:15px;line-height:107%;font-family:"Calibri",sans-serif;'>Vous avez toutes mon num&eacute;ro mais je le remets ici : +33649419033</span></p>
"""

  [[params.servicesfemmes.item]]
    icon = "icon-car"
    title = "Covoiturage Diemeringen"
    description = "VoiciÂ le lien de <a href='https://www.groupcarpool.com/t/y0gbqz' target='_blank'>covoiturage Outeya</a>  pour s'organniser au mieux.<br />Vous pouvez vous enregistrer comme conducteur ou passager. <a href='https://hisnii.com/invocation-du-voyageur/' target='_blank'>Ø¯Ø¹Ø§Ø¡ Ø§Ù„Ø³Ù Ø±</a>"

    [[params.servicesfemmes.item]]
    icon = "icon-camera"
    title = "Photos"
    description = "Attention, nous sommes une majoritÃ© de femmes qui portons le hijab, mais pour lâ€™occasion, on ne le portera pas donc je rappelle Ã  toutes les invitÃ©es de ne prendre aucune photo durant le sÃ©jour sans demander avant."


  [[params.servicesfemmes.item]]
    icon = "icon-music"
    title = "Playlist"
    description = "Je suis en train de mettre au point une liste de lecture pour la soirÃ©e et jâ€™ai besoin de votre aide ! A vous de complÃ©ter <a href='https://open.spotify.com/playlist/4RrWJpXPvuuAOL5aSeaRWZ?si=EjfM_I1IRQ2TJMmA7vwM6Q' target='_blank'>la playlist</a> (rien est interdit mais obligation de danser sur chacune des musiques ajoutÃ©es ğŸ˜‰ (ps : le lien fonctionne mieux sur application pc que sur smartphone, si Ã§a ne marche pas bien, envoyez moi les titres des musiques en message ğŸŒ¼)"

  [[params.servicesfemmes.item]]
    icon = "icon-magic-wand"
    title = "Dresscode"
    description = "PrÃ©voyez pour la journÃ©e, un t-shirt blanc et un jeans bleu please (pour les photos) ;  et de quoi vous sentir belle pour la soirÃ©e, aucun homme ne sera prÃ©sent. "

 [[params.servicesfemmes.item]]
    icon = "icon-present"
    title = "Cagnotte"
    description = "<a href='https://paypal.me/pools/c/8mQdcPAGFe' target='_blank'>Une cagnotte</a> pour nous aider durant nos premiers mois de vie commune est ouverte ici ğŸ˜Š mais votre prÃ©sence sera votre plus beau cadeau ! "

